version: "3"

services:
    backend:
        restart: always
        ports: 
            - "3000:3000"
        build : 
            dockerfile: Dockerfile
            context: ./backend
        stdin_open: true
        depends_on: 
            - mysql
        container_name: app_backend
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        build: 
            dockerfile: Dockerfile
            context: ./mysql
        restart: unless-stopped
        container_name: app_mysql
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_HOST: "172.19.0.2"
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: survey
            MYSQL_ROOT_HOST: '%'
        volumes: 
            - "./mysql/sqls/:/docker-entrypoint-initdb.d/"