module.exports = {
    surveyStartTime: "",
    surveyCompleteTime: "",
    email: "",
    emailDomain: "",
    name: "",
    experimentType: "",
    timeSaveScore: -1,
    dataIntegrityScore: -1,
    reflectOpnionScore: -1,
    responseTimeScore: -1,
    satisfyScore: -1,
    figureComment: "",
    figureCommentTxt: "",
    userOpinion: "",
};